apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress-1b
  template:
    metadata:
      labels:
        app: nginx-ingress-1b
    spec:
      serviceAccount: nginx
      containers:
      - name: nginx-ingress-controller
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 18080
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-backend
        - --configmap=$(POD_NAMESPACE)/nginx-ingress-controller-conf
        - --v=2
        env: 
        - name: POD_NAME 
          valueFrom: 
            fieldRef: 
              fieldPath: metadata.name 
        - name: POD_NAMESPACE 
          valueFrom: 
            fieldRef: 
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ingress-namespace
spec:
  type: NodePort
  ports: 
  - port: 80
    name: http
    nodePort: 32000
  - port: 18080
    name: http-mgmt
  selector:
    app: nginx-ingress-lb