apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: ingress-namespace
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata: 
  name: nginx-role
  namespace: ingress-namespace
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "nodes", "pods", "secrets"]
    verbs: ["watch", "list"] 
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"] 
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list", "update"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["extensions"]
    resources: ["ingresses/status"]
    verbs: ["update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
  name: nginx-role 
  namespace: ingress 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: nginx-role
  subjects: 
    - kind: ServiceAccount 
      name: nginx 
      namespace: ingress-namespace