kind: deployment
apiVersion: apps/v1
metadata:
  labels:
    app: hollowapp
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: hollowapp
  template:
    metadata:
      labels:
        app: hollowapp
    spec:
      containers:
      - name: hollowapp
        image: theithollow/hollowapp-blog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          value: "my-secret"
---
kind: Service
apiVersion: v1
metadata:
  name: hollowapp
  labels:
    app: hollowapp
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: hollowapp
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: hollowapp
  labels:
    app: hollowapp
spec:
  rules:
  - host: hollowapp.hollow.local
    http:
      paths:
      - path: /
        backend:
          name: hollowapp
          port: 
            number: 5000